---
- name: fqdn | Configure Debian
  import_tasks: debian.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: fqdn | Configure Redhat
  import_tasks: redhat.yml
  when: ansible_distribution in [ 'RedHat', 'CentOS' ]

- name: fqdn | Configure Linux
  import_tasks: linux.yml
  when: ansible_system in  [ "Linux" ]

- name: fqdn | Configure Windows
  import_tasks: windows.yml
  when: ansible_system in  [ "Win32NT" ]
